; PHP Condfiguration for Nextcloud
; This file is used to set PHP configuration values for Nextcloud.
; It is recommended to place this file in the PHP configuration directory
;Optimized PHP settings for Nextcloud

memory_limit = 512M
upload_max_filesize = 2G
post_max_size = 2G
max_execution_time = 360

;OPCache settings for improved performance
opcache.enable=1
opcache.interned_strings_buffer=16
opcache.max_accelerated_files=10000
opcache.memory_consumption=128
opcache.save_comments=1
opcache.revalidate_freq=1

